### PR TITLE
feat: add v2 to demo

### PR DESCRIPTION
**Pull request by Mhera17**

### CODE REVIEW

**Review by eburck — COMMENTED** [review]
Thank you Mher for the update - all works good.
Just one remark: We now have connector and eventslib newly available on PROD, as well. Please use the prod versions for this branch to have the demo app connecting with our PROD environment as it is today.

**Comment by Mhera17** [comment]
Hello @eburck.
can you please send links to connector builds and EventsLib?

**Comment by DomiKoch** [comment]
Hi @Mhera17 ,

https://static-app.connect.trustedshops.com/connector/connector.umd.js

https://static-app.connect.trustedshops.com/events/eventsLib.js

Greetings

**Comment by Mhera17** [comment]
Hello Dominik, thanks

**Review by eburck — APPROVED** [review]

**Pull request merged**
